config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path for the application
  root "invoices#index"

  # Defines the path for the send_email action
  post "/send_email", to: "invoices#send_email"

  # make CRUD paths available in addition to path helpers
  resources :invoices do
    resources :invoice_items, only: [:new, :create]
  end

  # clients paths are limited to new and create
  resources :clients, only: [:new, :create]
  resources :invoices do
    resources :invoice_items, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user

  # note plural here even if model is singular
  # - also, associated invoices are destroyed when client is destroyed
  has_many :invoices, dependent: :destroy
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :client
  belongs_to :user

  # associated invoice_items are destroyed when invoice is destroyed
  has_many :invoice_items, dependent: :destroy
end

app/models/invoice_item.rb
class InvoiceItem < ApplicationRecord
  belongs_to :invoice
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # associations
  has_many :clients, dependent: :destroy
  has_many :invoices, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def new
    @clients = Client.where(user: current_user)
    @client = Client.new
  end

  def create
    # merges the user_id into the client_params hash
    @client = Client.new(client_params.merge(user_id: current_user.id))
    if @client.save
      redirect_to clients_path
    else
      @clients = Client.where(user: current_user)
      render :new, status: :unprocessable_entity
    end
  end

  private

  def client_params
    # assigning user to client
    # params[:client][:user] = current_user
    params.require(:client).permit(:email, :name, :phone, :address)
  end
end

app/controllers/invoice_items_controller.rb
class InvoiceItemsController < ApplicationController
  def new
    @invoice = Invoice.includes(:invoice_items, :client).find(params[:invoice_id])
    @total = calculate_total(@invoice)
  end

  def create
    # foreign key is also assigned to the new invoice item, as required for association
    @invoice_item = InvoiceItem.new(invoice_item_params.merge(invoice_id: params[:invoice_id]))

    if @invoice_item.save
      redirect_to new_invoice_invoice_item_path(params[:invoice_id])
    else
      @invoice = Invoice.includes(:invoice_items, :client).find(params[:invoice_id])
      @total = calculate_total(@invoice)
      render :new, static: :unprocessable_entity
    end
  end

  private
  def calculate_total(invoice)
    total = 0
    invoice.invoice_items.each do |item|
      quantity = item.quantity
      price = item.price
      total += (quantity * price)
    end
    total
  end

  private
  def invoice_item_params
    params.require(:invoice_item).permit(:service, :quantity, :price)
  end
end

app/controllers/invoice_private_view_controller.rb
class InvoicePrivateViewController < ApplicationController
  def private_show
    # but this is dependent on the params[:id] being passed in
    # ie: what we are going to have is a url like this:
    # http://localhost:3000/invoices_private/:id in the routes.rb file
    # http://localhost:3000/invoices_private/1
    @invoice = Invoice.includes(:invoice_items, :client).find(params[:id])
    # then we will be able to render a form, possibly `render` then just call on an existing view?
    render 'invoices/show'
  end

  # likely to be a POST request
  def send_by_client_email
    #  from the turbo button_to thing
    email = params[:email]
    url = params[:url]

    UserMailer.with(email: email, url: url).send_email.deliver_later

    # redirect to the index page
    redirect_to invoices_path
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  # both root "invoices#index" and root "articles#index" will map to this controller action
  def index
    # eager loading, essentially a join.
    # @invoices = Invoice.includes(:invoice_items ,:client).all
    @invoices = Invoice.includes(:invoice_items ,:client).where(user: current_user)

    # total calculation, done via accompanying total value. Mapped to the invoice object.
    @totals = {}
    @invoices.each do |invoice|
      @totals[invoice] = calculate_total(invoice)
    end
  end

  def show
    @invoice = Invoice.includes(:invoice_items, :client).find(params[:id])
    @total = calculate_total(@invoice)
  end

  def destroy
    # this receives a DELETE invoice/:id request
    @invoice = Invoice.find(params[:id])
    @invoice.destroy
    # then we go back to the index page
    redirect_to invoices_path
  end

  def send_email
    UserMailer.with(mailer_params).send_email.deliver_later
    redirect_to root_path
  end

  def new
    @clients = Client.where(user: current_user)
    @invoice = Invoice.new
  end

  def create
    @invoice = Invoice.new(invoice_params.merge(user_id: current_user.id))
    if @invoice.save
      redirect_to new_invoice_invoice_item_path(@invoice)
    else
      @clients = Client.where(user: current_user)
      render :new, static: :unprocessable_entity
    end
  end

  private
  def calculate_total(invoice)
    total = 0
    invoice.invoice_items.each do |item|
      quantity = item.quantity
      price = item.price
      total += (quantity * price)
    end
    total
  end

  def mailer_params
    params.require(:mailer).permit(:email, :invoice_id)
  end

  def invoice_params
    params.require(:invoice).permit(:client_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/invoice_items_helper.rb
module InvoiceItemsHelper
end

app/helpers/invoice_private_view_helper.rb
module InvoicePrivateViewHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/clients/_client.html.erb
<li><%= client.email %></li>

app/views/clients/new.html.erb
<nav><%= link_to "< Back", invoices_path %></nav>

<h1>Creating a new Client!</h1>

<%= form_with model: @client do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %> <br>

    <%= form.label :email %>
    <%= form.email_field :email %> <br>

    <%= form.label :phone %>
    <%= form.number_field :phone %> <br>

    <%= form.label :address %>
    <%= form.text_field :address %> <br>

    <%# error for clients %>
    <% if @client.errors.any? %>
      <% @client.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    <% end %>
  </div>

  <div>
    <br>
    <%= form.submit %>
  </div>
<% end %>

<hr>

<h2>See Available Clients</h2>
<ul>
  <%# <%= render partial: "client", collection: @clients %>
  <% @clients.each do |client| %>
    <li>
      <%= "#{client.name}: #{client.email}" %>
    </li>
  <% end %>
</ul>

app/views/invoice_items/new.html.erb
<nav><%= link_to "< Back", invoices_path %></nav>

<h1>New Invoice Here!</h1>

<h2>Invoice Title: <%= "INV_#{@invoice.id}"%></h2>

<p>Client Email: <%= @invoice.client.email %></p>

<table>
  <tr>
    <th>Description</th>
    <th>Quantity</th>
    <th>Unit Price ($)</th>
    <th>Total ($)</th>
  </tr>
  <% @invoice.invoice_items.each do |invoice_item| %>
    <tr>
      <th><%= invoice_item.service %></th>
      <th><%= invoice_item.quantity %></th>
      <th><%= invoice_item.price %></th>
      <th><%= invoice_item.quantity * invoice_item.price %></th>
    </tr>
  <% end %>
</table>

<p>Amount due: <%= "$#{@total}" %></p>

<%# Here is creation form for the specific item%>
<h3>Creating a new invoice item</h3>
<%= form_with model: [@invoice, @invoice.invoice_items.build ] do |form| %>
  <div>
    <%= form.label :service %>
    <%= form.text_field :service %>
  </div>

  <div>
    <%= form.label :quantity %>
    <%= form.number_field :quantity, step: 1 %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.01 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= button_to "(Finished Modifying Invoice 👍)", root_path, method: :get %>

<%# Display all the errors here: %>
<% if @invoice_item && @invoice_item.errors.any? %>
  <hr>
  <p>Error Messages</p>
  <ul>
    <% @invoice_item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/invoices/index.html.erb
<h1>Invoices Here</h1>

<%# buttons %>
<ul>
  <li><%= button_to "(+ New Invoice)", new_invoice_path, method: :get %></li>
  <li><%= button_to "(+ New Client)", new_client_path, method: :get %></li>
</ul>

<%# list the invoices beneath this line %>
<% if @invoices.any? %>
  <table>
    <tr>
      <th>Invoice no.</th>
      <th>Client name</th>
      <th>Invoice total</th>
      <th>Buttons</th>
    </tr>
    <% @invoices.each do |invoice|%>
      <tr>
        <th>
          <%= link_to "INV_#{invoice.id}", invoice_path(invoice) %>
        </th>
        <th>
          <%= invoice.client.name %>
        </th>
        <th>
          <%= @totals[invoice] %>
        </th>
        <th>
          <button type="button">📝</button>
          <%= button_to "🗑️", invoice_path(invoice), method: :delete, data: {
            turbo_confirm: "Are you sure you want to delete this invoice?",
          } %>
          <%= button_to "☁️", send_email_path, mehtod: :post, data: {
            turbo_confirm: "Are you sure you want to EMAIL☁️ this invoice (#{invoice.id})?"
          }, params: {
            mailer: {
              invoice_id: invoice.id,
              email: invoice.client.email
            }
          } %></th>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>There are no invoices to be displayed. Please create an invoice 🙏 </p>
<% end %>

app/views/invoices/new.html.erb
<nav><%= link_to "< Back", invoices_path %></nav>
<h1>New Invoice</h1>

<%= form_for @invoice do |f| %>
  <%= f.label :client_email, 'Client name:' %>
  <%= f.collection_select :client_id, @clients, :id, :name, prompt: 'Select client' %>
  <% if @invoice.errors.any? %>
    <% @invoice.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>
  <%= f.submit 'Create invoice with Client' %>
<% end %>

app/views/invoices/show.html.erb
<nav><%= link_to "< Back", invoices_path %></nav>

<h1>Specific Invoice Here!</h1>

<h2>Invoice Title: <%= "INV_#{@invoice.id}"%></h2>

<p>Client Email: <%= @invoice.client.email %></p>

<table>
  <tr>
    <th>Description</th>
    <th>Quantity</th>
    <th>Unit Price ($)</th>
    <th>Total ($)</th>
  </tr>
  <% @invoice.invoice_items.each do |invoice_item| %>
    <tr>
      <th><%= invoice_item.service %></th>
      <th><%= invoice_item.quantity %></th>
      <th><%= invoice_item.price %></th>
      <th><%= invoice_item.quantity * invoice_item.price %></th>
    </tr>
  <% end %>
</table>

<p>Amount due: <%= "$#{@total}" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsInvoiceProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in? %>
      <div> Welcome <%= current_user.email %> </div>
      <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= button_to "Sign in", new_user_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>